// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuay4zAx-cuGSgvdNBgS0o6P1SCXFqjlA',
    appId: '1:940495523475:web:531ce1d4e0260242110766',
    messagingSenderId: '940495523475',
    projectId: 'sih24-c230a',
    authDomain: 'sih24-c230a.firebaseapp.com',
    storageBucket: 'sih24-c230a.appspot.com',
    measurementId: 'G-DKRTKZ18Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh0jnnre7LyD-5CudOxFeOlNMqzv_FrVg',
    appId: '1:940495523475:android:d85be9e9e4397f65110766',
    messagingSenderId: '940495523475',
    projectId: 'sih24-c230a',
    storageBucket: 'sih24-c230a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBcqDzmWN-kcHzJ-5nLBkRQ73L14R37KQ',
    appId: '1:940495523475:ios:0e52e3115ef47fcb110766',
    messagingSenderId: '940495523475',
    projectId: 'sih24-c230a',
    storageBucket: 'sih24-c230a.appspot.com',
    iosBundleId: 'com.example.sih24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBcqDzmWN-kcHzJ-5nLBkRQ73L14R37KQ',
    appId: '1:940495523475:ios:23b6117fdf94387c110766',
    messagingSenderId: '940495523475',
    projectId: 'sih24-c230a',
    storageBucket: 'sih24-c230a.appspot.com',
    iosBundleId: 'com.example.sih24.RunnerTests',
  );
}
